--liquibase formatted sql

--changeset Mody:001-1-create-structure
CREATE TABLE structure
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    actif   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT structure_pkey PRIMARY KEY (id),
    CONSTRAINT structure_libelle_key UNIQUE (libelle)
);

--changeset Mody:001-2-create-maladie-chronique
CREATE TABLE maladie_chronique
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    actif   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT maladie_chronique_pkey PRIMARY KEY (id),
    CONSTRAINT maladie_chronique_libelle_key UNIQUE (libelle)
);

--changeset Mody:001-3-create-facteur-de-risque
CREATE TABLE facteur_de_risque
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    actif   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT facteur_de_risque_pkey PRIMARY KEY (id),
    CONSTRAINT facteur_de_risque_libelle_key UNIQUE (libelle)
);

--changeset Mody:001-4-create-situation-sociale
CREATE TABLE situation_sociale
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    actif   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT situation_sociale_pkey PRIMARY KEY (id),
    CONSTRAINT situation_sociale_libelle_key UNIQUE (libelle)
);
