--liquibase formatted sql

--changeset Mody:002-1-create-medecin
CREATE TABLE medecin
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom                       VARCHAR(255) NOT NULL,
    prenom                    VARCHAR(255) NOT NULL,
    numero_ordre              VARCHAR(100) NOT NULL,
    role                      VARCHAR(20)  NOT NULL,
    structure_rattachement_id BIGINT,
    CONSTRAINT medecin_pkey PRIMARY KEY (id),
    CONSTRAINT medecin_numero_ordre_key UNIQUE (numero_ordre),
    CONSTRAINT fk_medecin_structure FOREIGN KEY (structure_rattachement_id) REFERENCES structure (id)
);
