--liquibase formatted sql

--changeset Mody:005-1-create-constante-vitale
CREATE TABLE constante_vitale
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consultation_id UUID          NOT NULL,
    type            VARCHAR(30)   NOT NULL,
    valeur          NUMERIC(7, 2) NOT NULL,
    heure           TIME,
    est_normal      BOOLEAN,
    est_alerte      BOOLEAN,
    commentaire     TEXT,
    CONSTRAINT constante_vitale_pkey PRIMARY KEY (id),
    CONSTRAINT fk_constante_consultation FOREIGN KEY (consultation_id) REFERENCES consultation_initiale (id)
);
CREATE INDEX idx_constante_consultation ON constante_vitale (consultation_id);

--changeset Mody:005-2-create-examen-par-appareil
CREATE TABLE examen_par_appareil
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consultation_id         UUID NOT NULL,
    etat_general            TEXT,
    cardio_vasculaire       TEXT,
    respiratoire            TEXT,
    digestif                TEXT,
    neurologique            TEXT,
    locomoteur_cutane_autre TEXT,
    CONSTRAINT examen_par_appareil_pkey PRIMARY KEY (id),
    CONSTRAINT examen_par_appareil_consultation_id_key UNIQUE (consultation_id),
    CONSTRAINT fk_examen_consultation FOREIGN KEY (consultation_id) REFERENCES consultation_initiale (id)
);

--changeset Mody:005-3-create-antecedent-maladie
CREATE TABLE antecedent_maladie
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consultation_id       UUID   NOT NULL,
    maladie_chronique_id  BIGINT NOT NULL,
    precision             TEXT,
    CONSTRAINT antecedent_maladie_pkey PRIMARY KEY (id),
    CONSTRAINT fk_antecedent_consultation FOREIGN KEY (consultation_id) REFERENCES consultation_initiale (id),
    CONSTRAINT fk_antecedent_maladie_chronique FOREIGN KEY (maladie_chronique_id) REFERENCES maladie_chronique (id)
);
CREATE INDEX idx_antecedent_consultation ON antecedent_maladie (consultation_id);
